# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session_type', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='visitation day')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthixtest.Doctor')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthixtest.Laboratory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthixtest.Patient')),
            ],
        ),
    ]
