# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthixtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen', models.CharField(max_length=200)),
                ('lab_test', models.CharField(max_length=600)),
                ('duration', models.CharField(max_length=100)),
                ('date_requested', models.DateTimeField(verbose_name='date requested')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='doctor', max_length=200),
        ),
        migrations.AddField(
            model_name='laboratory_test',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthixtest.Doctor'),
        ),
        migrations.AddField(
            model_name='laboratory_test',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthixtest.Laboratory'),
        ),
        migrations.AddField(
            model_name='laboratory_test',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthixtest.Patient'),
        ),
    ]
