# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthixtest', '0002_auto_20170304_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory_Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('password', models.CharField(default='laboratory', max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthixtest.Laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='laboratory_test',
            name='result',
            field=models.CharField(default='pending', max_length=1200),
        ),
    ]
